# Generated by Django 5.1.3 on 2024-11-15 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('torneio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Torneio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneios', to='jogos.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timea', models.CharField(max_length=50)),
                ('timeb', models.CharField(max_length=50)),
                ('horario', models.DateTimeField()),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jogos.torneio')),
            ],
        ),
    ]
