# Generated by Django 5.1.3 on 2024-11-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
    ]
