# Generated by Django 5.1.3 on 2024-11-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_alter_pais_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='torneio',
        ),
        migrations.DeleteModel(
            name='Torneio',
        ),
    ]
