# Generated by Django 5.1.3 on 2024-11-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_alter_pais_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='pais',
            field=models.CharField(max_length=50, null=True, verbose_name='País'),
        ),
    ]
