# Generated by Django 5.1.3 on 2024-11-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_jogo_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='observacoes',
            field=models.TextField(null=True, verbose_name='Observações'),
        ),
    ]
