# Generated by Django 5.1.3 on 2025-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0007_jogo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='timea',
            field=models.CharField(max_length=50, verbose_name='Time A'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='timeb',
            field=models.CharField(max_length=50, verbose_name='Time B'),
        ),
    ]
